export function generateVideoMeta(topic, channelName) {
  return {
    title: `🔥 ${topic} | Must Watch`,
    description: `
🎬 Title: ${topic}

📺 Channel: ${channelName}

🔥 This video is auto-generated by YouTube Automation System.

#automation #youtube #viral
    `,
  };
}

